- README.md
Hey I changed something, can I have a code review?
> Test for Merge

- test.text
I added a test.text file for testing
> add test file

- antraShares/README.md
Loc Luu try to merge
@johnkramorbhz
> changed st

- Share_project/src/app/login/login.module.ts
- Share_project/src/app/news-feed/news-feed.module.ts
- Share_project/src/app/profile/profile.module.ts
- Share_project/src/app/settings/settings.module.ts
> added modules

- teamProject/package-lock.json
- teamProject/src/app/app.module.ts
- teamProject/src/app/pages/login/register-form/mustMatch.validator.ts
- teamProject/src/app/pages/login/register-form/register-form.component.html
- teamProject/src/app/pages/login/register-form/register-form.component.ts
@jianfengchi1998 @jie-ying please take a look at this.
> feature/F2A-37/RegisterPage/kru  --- registerPage validation

- teamProject/package-lock.json
- teamProject/src/app/app.module.ts
- teamProject/src/app/components/storycard/storycard.component.html
- teamProject/src/app/components/storycard/storycard.component.less
- teamProject/src/app/components/storycard/storycard.component.ts
- teamProject/src/app/pages/login/register-form/mustMatch.validator.ts
- teamProject/src/app/pages/login/register-form/register-form.component.html
- teamProject/src/app/pages/login/register-form/register-form.component.ts
- teamProject/src/app/pages/newsfeed/newsfeed.component.ts
- teamProject/src/app/pages/newsfeed/newsfeed.module.ts
- teamProject/src/app/services/newsfeed.service.ts
@jianfengchi1998 @jie-ying please take a look at this.
> Feature/F2A-55/commentsDialogPopup/kru --- popup window for comments

- TeamProject/package-lock.json
- TeamProject/src/app/interfaces/news.model.ts
- TeamProject/src/app/modules/news-feed/news-feed.module.ts
- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/comment-dialog/comment-dialog.component.css
- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/comment-dialog/comment-dialog.component.html
- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/comment-dialog/comment-dialog.component.spec.ts
- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/comment-dialog/comment-dialog.component.ts
- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/story-card.component.html
- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/story-card.component.ts
@SuchenShi @ardithoxha code review
> Feature/aba/by jason/newsfeed dialog

- TeamProject/package-lock.json
- TeamProject/src/app/app.module.ts
- TeamProject/src/app/modules/login/login-page/login-page.component.css
- TeamProject/src/app/modules/login/login-page/login-page.component.html
- TeamProject/src/app/modules/login/login-page/login-page.component.spec.ts
- TeamProject/src/app/modules/login/login-page/login-page.component.ts
- TeamProject/src/app/modules/login/login.module.ts
@jqj5405 @ardithoxha Register reactive input form with validators created. Please have a check!
> Register Form finished

- .vscode/settings.json
- antra_final/src/app/app.component.html
- antra_final/src/app/login/login.module.ts
- antra_final/src/app/login/register/register.component.html
- antra_final/src/app/login/register/register.component.scss
- antra_final/src/app/login/register/register.component.ts
Here is my register page, please review and or approve!
> Feature/lkt/by luke/register

- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/comment-dialog/comment-dialog.component.css
- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/comment-dialog/comment-dialog.component.html
- TeamProject/src/app/modules/news-feed/newsfeed-page/story-card/comment-dialog/comment-dialog.component.ts
@ardithoxha @SuchenShi code review
> Feature/aba/by jason/comment pagination

- package-lock.json
- teamProject/src/app/pages/login/login-form/login-form.component.html
> merge issue fixed

- TeamProject/src/app/modules/login/login-page/login-page.component.css
- TeamProject/src/app/modules/login/login-page/login-page.component.html
- TeamProject/src/app/modules/login/login-page/login-page.component.ts
- TeamProject/src/app/modules/login/login.module.ts
@jqj5405 @ardithoxha Code review for loginUpdate
> loginpage updated

- TeamProject/src/app/modules/login/login-page/login-page.component.css
- TeamProject/src/app/modules/login/login-page/login-page.component.html
- TeamProject/src/app/modules/login/login-page/login-page.component.ts
- TeamProject/src/app/modules/login/login.module.ts
Reverts David3567/Antra-Share-Feb-2022#87
> Revert "loginpage updated"

- Sprint1/package-lock.json
- Sprint1/package.json
- Sprint1/src/app/app-routing.module.ts
- Sprint1/src/app/app.component.html
- Sprint1/src/app/app.component.scss
- Sprint1/src/app/app.module.ts
- Sprint1/src/app/services/userlist.service.ts
- Sprint1/src/styles.scss
Reverts David3567/Antra-Share-Feb-2022#93
> Revert "Feature/laureate/by joey/loginupdate"

- package-lock.json
- teamProject/package-lock.json
- teamProject/src/app/app.module.ts
- teamProject/src/app/interfaces/backEndUser.model.ts
- teamProject/src/app/pages/login/register-form/register-form.component.html
- teamProject/src/app/pages/login/register-form/register-form.component.ts
- teamProject/src/app/services/authen.service.spec.ts
- teamProject/src/app/services/authen.service.ts
Please review @jie-ying @jianfengchi1998
> Feature/f2 a 74/register auth/kru

- package-lock.json
- teamProject/package-lock.json
- teamProject/src/app/app.module.ts
- teamProject/src/app/interfaces/backEndUser.model.ts
- teamProject/src/app/pages/login/login-form/login-form.component.html
- teamProject/src/app/pages/login/login-form/login-form.component.ts
- teamProject/src/app/pages/login/register-form/register-form.component.html
- teamProject/src/app/pages/login/register-form/register-form.component.ts
- teamProject/src/app/services/authen.service.spec.ts
- teamProject/src/app/services/authen.service.ts
Please review @jianfengchi1998 @jie-ying
> Feature/f2 a 68/login auth/kru

- TeamProject/src/app/app-routing.module.ts
- TeamProject/src/app/interfaces/users.model.ts
- TeamProject/src/app/modules/login/login-page/login-page.component.ts
- TeamProject/src/app/modules/login/register-page/register-page.component.css
- TeamProject/src/app/modules/login/register-page/register-page.component.html
- TeamProject/src/app/modules/login/register-page/register-page.component.ts
- TeamProject/src/app/services/login.service.ts
- TeamProject/src/app/services/register.service.ts
@jqj5405 @SuchenShi, code review for register service and login service.
> Feature/aba/by ardit/register service

- TeamProject/src/app/app.module.ts
- TeamProject/src/app/interceptors/auth.interceptor.spec.ts
- TeamProject/src/app/interceptors/auth.interceptor.ts
- TeamProject/src/app/services/login.service.ts
- TeamProject/src/app/services/profile-guard.service.ts
@ardithoxha @SuchenShi code review
- Enable middleware 'auth' in news.js get('/')
- Make sure no token exists or use a JWT token that doesn't exist in database when checking newsfeed page
- Sample token that doesn't exist in database
```bash
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```
> Feature/aba/by jason/interceptor

- TeamProject/src/app/modules/login/register-page/register-page.component.css
- TeamProject/src/app/modules/login/register-page/register-page.component.html
- TeamProject/src/app/modules/login/register-page/register-page.component.ts
- TeamProject/src/app/modules/profile/profile-page/profile-page.component.html
- TeamProject/src/app/modules/profile/profile-page/profile-page.component.ts
@SuchenShi @ardithoxha code review
> Add checkbox validator; revise error code display

- TeamProject/src/app/app.module.ts
- TeamProject/src/app/interfaces/users.model.ts
- TeamProject/src/app/modules/admin/admin-page/admin-page.component.css
- TeamProject/src/app/modules/admin/admin-page/admin-page.component.html
- TeamProject/src/app/modules/admin/admin-page/admin-page.component.ts
- TeamProject/src/app/modules/admin/admin-page/user-info-panel/user-info-panel.component.css
- TeamProject/src/app/modules/admin/admin-page/user-info-panel/user-info-panel.component.html
@ardithoxha @jqj5405 code review for admin page updated
> admin page updated
